### ISSUE TITLE
Search fails on multiple matches

### ISSUE THREAD

**Issue by dkensiski** [vmoa/imagelib#1]
Reported by: George Loyer

Clear the date search field and enter Z UMi (for example). The autosuggest target for the search brings up two options, GCVS Z UMi and GCVS5 Z UMi.  Leaving the text in the search field as Z UMi and clicking on Search gets an Internal Server error.  Choosing either of the autosuggest targets results in a successful search.  Expected behavior is that the search would return results that matched any object with Z UMi in the name field.

**Comment by dkensiski** [comment]
Tagging @georgeloyer in the hopes that this will send him updates.

**Comment by georgeloyer** [comment]
This is tested and fixed, nice work, really adds to the value of the tool.

**Comment by georgeloyer** [comment]
Confirmed that the fix is complete with DaveK
